# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ecomexperts-x-cart-transform"
client_id = "7d204cf6d1ae90e758a715e88c182815"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_products,write_products,write_price_rules,write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
